---
# tasks file for client
- name: copy static key to server
  copy:
    src: ../static.key
    dest: /etc/openvpn/static.key

- name: create server.conf
  template:
    src: server.conf
    dest: /etc/openvpn/server.conf
  notify:
    - restart openvpn

- name: enable/start openvpn
  systemd:
    name: openvpn@server
    enabled: yes
    state: started

